####################
## Taps            #
####################
tap "caarlos0/tap"
tap "domt4/autoupdate"
tap "github/gh"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "mveritym/mel"
tap "buo/cask-upgrade"
tap "salesforce/policy_sentry"
tap "aws/tap"
tap "homebrew/cask-drivers"

####################
## Shell           #
####################
cask "iterm2"
brew "bat"
brew "fzf"
brew "shellcheck"
brew "sshuttle"
brew "yq"
brew "tree"
brew "zsh-syntax-highlighting"
cask "session-manager-plugin"

####################
## Dev Env         #
####################
brew "act"
brew "awscli"
brew "gh"
brew "git"
brew "git-lfs"
brew "jq"
cask "docker"
cask "visual-studio-code"
cask "github"
cask "postman"
brew "gnupg"
brew "policy_sentry"

####################
## JS/TS           #
####################
brew "node", link: false
brew "yarn"

####################
## Apps & Utils    #
####################
cask "authy"
cask "krisp"
cask "spotify"
cask "typora"
cask "logi-options-plus" # for logitech mx master mouse


####################
## Mac App Store   #
####################
mas "Magnet", id: 441258766
mas "Xcode", id: 497799835



####################################
## TBD/Installed a different way   #
####################################
## Slated for archival
# brew "make" # managed via Roam, maybe?
# brew "ec2-metadata-mock"
# brew "kustomize"
# brew "mveritym/mel/kubedecode"
# brew "pure"
# brew "telnet"
# brew "transcrypt"
# brew "volta"
